#!/usr/bin/env sh
set -e

#    create_deploy2zenodo_gitlab_ci_pipeline
#    Copyright (C) 2023  Daniel Mohr

echo "run create_deploy2zenodo_gitlab_ci_pipeline"

IN=deploy2zenodo
OUT=deploy2zenodo.yaml

VERSION=$(sed -n 's/^.*Version:\s*\(\S*\)$/\1/p' $IN)
URL=$(sed -n 's/^home:\s*\(https:\S*\)$/\1/p' README.md)

script=$(sed -n '/^#    deploy2zenodo$/,/^# stop deploy2zenodo$/p' $IN | \
	     sed '/^\s*$/d' | \
	     sed '/^VERSION=.*$/d' | \
	     sed "s#v\$VERSION#v$VERSION $URL-/releases/$VERSION#g" | \
	     sed 's/^/      /')

cat >$OUT <<EOL
.deploy2zenodo:
  script:
    - |
$script

deploy2zenodo:
  stage: .post
  image:
    name: alpine:latest
  before_script:
    - apk add --no-cache curl jq
  extends: .deploy2zenodo
EOL
