#!/usr/bin/env bash
set -e

#    deploy2zenodo
#    Copyright (C) 2023  Daniel Mohr
#    Version: 0.0.4
#
# Instead of command line parameters we use environment variables.
# You have to provide:
#   * DEPLOY2ZENODO_API_URL
#   * DEPLOY2ZENODO_ACCESS_TOKEN
#   * DEPLOY2ZENODO_DEPOSITION_ID
#   * DEPLOY2ZENODO_JSON
#   * DEPLOY2ZENODO_UPLOAD
# For more information see:
# https://gitlab.com/daniel_mohr/deploy2zenodo

VERSION=$(sed -n 's/^.*Version:\s*\(\S*\)$/\1/p' "$0")

echo "run deploy2zenodo v$VERSION"

# check available variables
missing_variables=""
for varname in DEPLOY2ZENODO_API_URL DEPLOY2ZENODO_ACCESS_TOKEN DEPLOY2ZENODO_DEPOSITION_ID DEPLOY2ZENODO_JSON DEPLOY2ZENODO_UPLOAD; do
    if [ -z ${!varname} ]; then
	missing_variables="$missing_variables $varname"
    fi
done

if [ -n "$missing_variables" ]; then
    echo "ERROR: you have to provide environment variables"
    echo "missing variables are at least:$missing_variables"
    exit 1
fi

set -x

echo "TAG: $TAG"

if [ "$DEPLOY2ZENODO_DEPOSITION_ID" = "create NEW record" ]; then
    # create new record
    #   * upload metadata
    #   * upload files/archive
    #   * publish
else
    # update record
    #   * get data from record
    #   * create new version
    #   * update metadata
    #   * remove all files from new version
    #   * upload files/archive
    #   * publish
fi

# stop deploy2zenodo
