#!/usr/bin/env sh
set -e

#    deploy2zenodo
#    Copyright (C) 2023  Daniel Mohr
#    Version: 0.4.0
#
# Instead of command line parameters we use environment variables.
#
# You have to provide:
#   * DEPLOY2ZENODO_API_URL
#   * DEPLOY2ZENODO_ACCESS_TOKEN
#   * DEPLOY2ZENODO_DEPOSITION_ID
#   * DEPLOY2ZENODO_JSON
#   * DEPLOY2ZENODO_UPLOAD
#
# And there are optional variables you can provide:
#   * DEPLOY2ZENODO_SKIP_PUBLISH
#   * DEPLOY2ZENODO_DRYRUN
#   * DEPLOY2ZENODO_SKIPRUN
#   * DEPLOY2ZENODO_SKIP_NEW_VERSION
#   * DEPLOY2ZENODO_GET_METADATA
#
# For more information see: https://gitlab.com/deploy2zenodo/deploy2zenodo
#
# Copyright 2023 Daniel Mohr and
#    Deutsches Zentrum fuer Luft- und Raumfahrt e. V., D-51170 Koeln
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION=$(sed -n 's/^.*Version:\s*\(\S*\)$/\1/p' "$0")

echo "run deploy2zenodo v$VERSION"

# check available variables
missing_variables=""
for varname in DEPLOY2ZENODO_API_URL DEPLOY2ZENODO_ACCESS_TOKEN DEPLOY2ZENODO_DEPOSITION_ID DEPLOY2ZENODO_JSON DEPLOY2ZENODO_UPLOAD; do
    if [ -z "$(eval "echo \"\$$varname\"")" ]; then
	missing_variables="$missing_variables $varname"
    fi
done

if [ -n "$missing_variables" ]; then
    echo "ERROR: you have to provide environment variables"
    echo "missing variables are at least:$missing_variables"
    exit 1
else
    for varname in DEPLOY2ZENODO_API_URL DEPLOY2ZENODO_DEPOSITION_ID DEPLOY2ZENODO_JSON DEPLOY2ZENODO_UPLOAD DEPLOY2ZENODO_SKIP_PUBLISH DEPLOY2ZENODO_DRYRUN DEPLOY2ZENODO_SKIPRUN; do
	echo "$varname: $(eval "echo \"\$$varname\"")"
    done
fi

if [ -n "$DEPLOY2ZENODO_DRYRUN" ] || [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
    curl() {
	echo "$@" > /dev/null
    }
fi
if [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
    jq() {
	echo "$@" > /dev/null
    }
    md5sum() {
	echo "$@" > /dev/null
    }
fi

hjson='Content-Type: application/json'
hauth="Authorization: Bearer $DEPLOY2ZENODO_ACCESS_TOKEN"

set -x

jq -C . "$DEPLOY2ZENODO_JSON"

if [ "$DEPLOY2ZENODO_DEPOSITION_ID" = "create NEW record" ]; then
    # create new record
    echo "create new record"
    #   * create new record and upload metadata
    NEWRECORD="$(curl --header "$hjson" --header "$hauth" --request POST --data-binary "$(cat "$DEPLOY2ZENODO_JSON")" "$DEPLOY2ZENODO_API_URL"/deposit/depositions)"
    echo "$NEWRECORD" | jq -C .
    DEPLOY2ZENODO_DEPOSITION_ID=$(echo "$NEWRECORD" | jq .id)
    LATESTID=$DEPLOY2ZENODO_DEPOSITION_ID
    test "$DEPLOY2ZENODO_DEPOSITION_ID" != "null"
    echo "##################################################################"
    echo "# add the id of the deposition/record on zenodo for the next run #"
    echo "# id: $DEPLOY2ZENODO_DEPOSITION_ID"
    echo "#                                                                #"
    echo "# DEPLOY2ZENODO_DEPOSITION_ID=$DEPLOY2ZENODO_DEPOSITION_ID"
    echo "##################################################################"
    BUCKETURLRAW=$(echo "$NEWRECORD" | jq .links.bucket)
    test "$BUCKETURLRAW" != "null"
    BUCKETURL=$(echo "$BUCKETURLRAW" | sed 's/"//g')

    #   * upload files/archives
    for filename in $DEPLOY2ZENODO_UPLOAD; do
	FILEUPLOAD=$(curl --header "$hauth" --upload-file "$filename" "$BUCKETURL"/"$(basename "$filename")")
	echo "$FILEUPLOAD" | jq -C .
	CHECKSUM=$(echo "$FILEUPLOAD" | jq .checksum)
	test "$CHECKSUM" != "null"
	CHECKSUM=$(echo "$CHECKSUM" | sed 's/"//g' | cut -d ':' -f 2)
	if [ -n "$DEPLOY2ZENODO_DRYRUN" ] || [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
	    echo "Skip testing checksum due to DRYRUN or SKIPRUN."
	else
	    echo "$CHECKSUM  $filename" | md5sum -c -
	fi
    done

    #   * publish
    if [ -n "$DEPLOY2ZENODO_SKIP_PUBLISH" ]; then
	echo "#################################################"
	echo "# --> Publishing is skipped!                    #"
	echo "# --> You have to publish this record manually! #"
	echo "#################################################"
    else
	PUBLISHRECORD=$(curl --max-time 300 --header "$hauth" --request POST "$DEPLOY2ZENODO_API_URL"/deposit/depositions/"$DEPLOY2ZENODO_DEPOSITION_ID"/actions/publish)
	echo "$PUBLISHRECORD" | jq -C .
	if [ -n "$DEPLOY2ZENODO_DRYRUN" ] || [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
	    echo "Skip testing result due to DRYRUN or SKIPRUN."
	else
	    test "$(echo "$PUBLISHRECORD" | jq .state)" = '"done"'
	    test "$(echo "$PUBLISHRECORD" | jq .submitted)" = "true"
	fi
    fi
    echo "##################################################################"
    echo "# add the id of the deposition/record on zenodo for the next run #"
    echo "# id: $DEPLOY2ZENODO_DEPOSITION_ID"
    echo "#                                                                #"
    echo "# DEPLOY2ZENODO_DEPOSITION_ID=$DEPLOY2ZENODO_DEPOSITION_ID"
    echo "##################################################################"
else
    # update record
    echo "update record"
    #   * get data from record
    RECORD=$(curl --header "$hauth" "$DEPLOY2ZENODO_API_URL"/deposit/depositions/"$DEPLOY2ZENODO_DEPOSITION_ID")
    echo "$RECORD" | jq -C .
    NEWVERSIONURLRAW=$(echo "$RECORD" | jq .links.newversion)
    test "$NEWVERSIONURLRAW" != "null"
    NEWVERSIONURL=$(echo "$NEWVERSIONURLRAW" | sed 's/"//g')

    #   * create new version
    if [ -n "$DEPLOY2ZENODO_SKIP_NEW_VERSION" ]; then
	echo "#########################################"
	echo "# --> Creating new version is skipped!  #"
	echo "# --> Try to find latest draft.         #"
	echo "#########################################"
	conceptrecidraw=$(echo "$RECORD" | jq .conceptrecid)
	conceptrecid=$(echo "$conceptrecidraw" | sed 's/"//g')
	#LISTRES=$(curl --header "Authorization: Bearer $DEPLOY2ZENODO_ACCESS_TOKEN" "$DEPLOY2ZENODO_API_URL"/deposit/depositions?all_versions=1)
	LISTRES=$(curl --header "Authorization: Bearer $DEPLOY2ZENODO_ACCESS_TOKEN" "$DEPLOY2ZENODO_API_URL"/deposit/depositions?conceptrecid="$conceptrecid")
	LATESTRECORDPRE=$(echo "$LISTRES" | jq ".[] | select(.conceptrecid==\"$conceptrecid\" and .state!=\"done\")")
	LATESTID=$(echo "$LATESTRECORDPRE" | jq .id)
	LATESTRECORD=$(curl --header "$hauth" "$DEPLOY2ZENODO_API_URL/deposit/depositions/$LATESTID")
	LATESTDRAFTRAW=$(echo "$LATESTRECORD" | jq .links.latest_draft)
	test "$LATESTDRAFTRAW" != "null"
	LATESTDRAFT=$(echo "$LATESTDRAFTRAW" | sed 's/"//g')
	BUCKETURLRAW=$(echo "$LATESTRECORD" | jq .links.bucket)
	test "$BUCKETURLRAW" != "null"
	test "$BUCKETURL" != "null"
    else
	NEWVERSION=$(curl --header "$hauth" --request POST "$NEWVERSIONURL")
	echo "$NEWVERSION" | jq -C .
	LATESTDRAFTRAW=$(echo "$NEWVERSION" | jq .links.latest_draft)
	test "$LATESTDRAFTRAW" != "null"
	LATESTDRAFT=$(echo "$LATESTDRAFTRAW" | sed 's/"//g')
	BUCKETURLRAW=$(echo "$NEWVERSION" | jq .links.bucket)
	test "$BUCKETURLRAW" != "null"
	BUCKETURL=$(echo "$BUCKETURLRAW" | sed 's/"//g')
	LATESTID=$(echo "$NEWVERSION" | jq .id)
    fi

    #   * update metadata
    UPLOADMETADATA=$(curl --header "$hauth" --header "$hjson" --request PUT --data-binary "$(cat "$DEPLOY2ZENODO_JSON")" "$LATESTDRAFT")
    echo "$UPLOADMETADATA" | jq -C .

    #   * remove all files from new version
    for id in $(echo "$UPLOADMETADATA" | jq ".files[] | .id"); do
	id=$(echo "$id" | sed 's/"//g')
	echo "$id"
	DELETEFILE=$(curl --header "$hauth" --request DELETE "$LATESTDRAFT"/files/"$id")
	echo "$DELETEFILE" | jq -C .
    done

    #   * upload files/archives
    for filename in $DEPLOY2ZENODO_UPLOAD; do
	FILEUPLOAD=$(curl --header "$hauth" --upload-file "$filename" "$BUCKETURL"/"$(basename "$filename")")
	echo "$FILEUPLOAD" | jq -C .
	CHECKSUM=$(echo "$FILEUPLOAD" | jq .checksum)
	test "$CHECKSUM" != "null"
	CHECKSUM=$(echo "$CHECKSUM" | sed 's/"//g')
	CHECKSUM=$(echo "$CHECKSUM" | cut -d ':' -f 2)
	if [ -n "$DEPLOY2ZENODO_DRYRUN" ] || [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
	    echo "Skip testing checksum due to DRYRUN or SKIPRUN."
	else
	    echo "$CHECKSUM  $filename" | md5sum -c -
	fi
    done

    #   * publish
    if [ -n "$DEPLOY2ZENODO_SKIP_PUBLISH" ]; then
	echo "#################################################"
	echo "# --> Publishing is skipped!                    #"
	echo "# --> You have to publish this record manually! #"
	echo "#################################################"
    else
	PUBLISHRECORD=$(curl --max-time 300 --header "$hauth" --request POST "$LATESTDRAFT"/actions/publish)
	echo "$PUBLISHRECORD" | jq -C .
	if [ -n "$DEPLOY2ZENODO_DRYRUN" ] || [ -n "$DEPLOY2ZENODO_SKIPRUN" ]; then
	    echo "Skip testing result due to DRYRUN or SKIPRUN."
	else
	    test "$(echo "$PUBLISHRECORD" | jq .state)" = '"done"'
	    test "$(echo "$PUBLISHRECORD" | jq .submitted)" = "true"
	fi
	LATESTID=$(echo "$PUBLISHRECORD" | jq .id)
    fi
fi
if [ -n "$DEPLOY2ZENODO_GET_METADATA" ]; then
    LATESTMETADATA=$(curl --header "$hauth" "$DEPLOY2ZENODO_API_URL"/deposit/depositions/"$LATESTID" | tee "$DEPLOY2ZENODO_GET_METADATA")
    echo "$LATESTMETADATA" | jq -C .
    test "$(echo "$LATESTMETADATA" | jq .id)" = "$LATESTID"
fi

# stop deploy2zenodo
